name: Build/release

on: workflow_dispatch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Build and release with electron-builder
        run: |
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          yarn
          if [ "$RUNNER_OS" == "Linux" ]; then
              yarn dist -c.snap.publish=github
          elif [ "$RUNNER_OS" == "Windows" ]; then
              yarn dist
          elif [ "$RUNNER_OS" == "macOS" ]; then
              yarn dist -m --x64 --arm64
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        shell: bash
