name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:        
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 17
      
      - name: Setup GIT token
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.github_token }}
          name: Agampreet Singh
          
      - name: Build and release with electron-builder
        run:  |
          yarn install
          yarn dist
  
