name: CI

on: workflow_dispatch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Build with Electron Builder
        run: |
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          yarn
          if [ "$RUNNER_OS" == "Linux" ]; then
              yarn dist --publish never
          elif [ "$RUNNER_OS" == "Windows" ]; then
              yarn dist --publish never
          elif [ "$RUNNER_OS" == "macOS" ]; then
              yarn dist -m --x64 --arm64 --publish never
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-dist
          path: |
            release/*.exe
            release/*.dmg
            release/*.deb
            release/*.snap
            release/*.tar.gz
            release/*.AppImage
            release/*.rpm
